services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mix
      POSTGRES_PASSWORD: mix
      POSTGRES_DB: mixcampeao
    ports:
      - "5433:5432"
    volumes:
      - mixcampeao_db:/var/lib/postgresql/data

volumes:
  mixcampeao_db:

